#!/bin/bash
DIR="$( cd -P "$( dirname "$0" )" && pwd )"
source $DIR/env.sh

CMAKE_ARGS="-DPYTHON_VERSION=3.7"
CMAKE_ARGS+=" -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}"
CMAKE_ARGS+=" -DCMAKE_CXX_COMPILER=clang++"
CMAKE_ARGS+=" -DCMAKE_CXX_COMPILER_AR=llvm-ar"
CMAKE_ARGS+=" -DCMAKE_CXX_COMPILER_RANLIB=llvm-ranlib"
CMAKE_ARGS+=" -DCMAKE_EXE_LINKER_FLAGS=-lGLU"
CMAKE_ARGS+=" -DPYTHON_LIBRARY=${PY_LIB}"
CMAKE_ARGS+=" -DPYTHON_LIBPATH=${MAUCPY}/lib"
CMAKE_ARGS+=" -DPYTHON_INCLUDE_DIR=${MAUCPY}/include/python3.7m"
CMAKE_ARGS+=" -DWITH_OPENCOLLADA=ON"
CMAKE_ARGS+=" -DWITH_OPENCOLORIO=ON"
#CMAKE_ARGS+=" -DWITH_CYCLES_CUDA_BINARIES=ON"
CMAKE_ARGS+=" -DWITH_CYCLES_STANDALONE=ON"
CMAKE_ARGS+=" -DWITH_CYCLES_STANDALONE_GUI=ON"
CMAKE_ARGS+=" -DWITH_MOD_OCEANSIM=ON"
CMAKE_ARGS+=" -DWITH_FFTW3=ON"
mkdir ${BUILD_DIR}
pushd ${BUILD_DIR}
cmake ${CMAKE_ARGS} ${ROOT_DIR}
# cmake --build . -j ${NUM_BUILD_PROCS}
popd
