name: freecad-blender
channels:
  - pythonocc
  - tpaviot
  - oce
  - dlr-sc
  - conda-forge
  - defaults
  - ifcopenshell
  - freecad
  - gsecars
dependencies:
  - matplotlib
  - netcdf4
  - pyside2
  - boost
  - ca-certificates
  - certifi
  - compas
  - requests
  - jedi
  - numpy
  - oce
  - openssl
  - pip
  - python=3.7
  - pythonocc-core=0.18.2
  - neovim
  - flake8
  - pylint
  - pycodestyle
  - shiboken
    #- pip:
    #- shiboken
